version: '3'

tasks:
  run:
    cmds:
      - task -d frontend format
      - task -d backend run
  build:
    cmds:
      - task -d frontend format
      - task -d backend install-package
  build-docker-image:
    deps:
      - build
    cmds:
      - docker build -t lvick86/dockerapp:latest .
  
  run-docker-container:
    deps:
      - build-docker-image
    cmds:
      - docker run lvick86/dockerapp:latest
      
  push-docker-image:
    deps:
      - build-docker-image
    cmds:
      - docker push lvick86/dockerapp:latest
  

