version: '3'

tasks:
  run:
    cmds:
      - task -d frontend format
      - task -d backend run
  build:
    cmds:
      - task -d frontend format
      - task -d backend install-package
  build-docker-image:
    deps:
      - build
    cmds:
      - task clean-docker-image -f
      - docker build -t lvick86/dockerapp:latest .
  
  run-docker-container:
    deps:
      - build-docker-image
    cmds:
      - docker run -p 3000:3000 lvick86/dockerapp:latest
  
  clean-docker-image:
    cmds:
      - docker rm -f $(docker ps -aq --filter ancestor=lvick86/dockerapp:latest) | true
      - docker rmi lvick86/dockerapp:latest | true
  push-docker-image:
    deps:
      - build-docker-image
    cmds:
      - docker push lvick86/dockerapp:latest
  

